[env:bluepill_f103c8]
platform = ststm32
framework = arduino
board = bluepill_f103c8
board_build.core = maple
upload_protocol = stlink
debug_tool = stlink

lib_deps = 
	Wire @ ^1.0
	SPI @ ^1.0

board_build.ldscript = jtag_c8.ld
